name: ğŸ¤¸ğŸ½ Integrate & Deploy
on: [push]
permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ğŸ¤¸ğŸ½ lint, build & deploy
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: ğŸ›¡ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ğŸ‘ Clone Git Repo
        uses: actions/checkout@v3

      - name: ğŸ¦€ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: â›“ Install Node deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false  
      
      - name: ğŸ¦• Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.22

      - name: ğŸ”¬ Lint
        run: npm run lint

      - name: Install wasm-ack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: ğŸ’¿ Remix Build
        run: npm run build
      # TODO: vendor..?

      # TODO fork action so only upload public & build dirs
      #      then skip this step
      - name: ğŸ—‘ï¸ Throw out deps
        run: rm -rf ./packages/remix-app/node_modules

      - name: ğŸ“‚ Make deno dir
        run: mkdir ./deno

      - name: ğŸ“ Copy Remix build files into outut dir
        run: cp -R ./packages/remix-app/{build,public} ./deno

      - name: ğŸ“ Copy Rust WASM package files into output dir
        run: mkdir -p ./deno/rust_functions/build/ && cp -R ./packages/rust_functions/build/browser ./deno/rust_functions/build

      - name: ğŸ” List file contents of root
        run: tree ./
      
      - name: ğŸ” List file contents of deno dir
        run: tree ./deno

      - name: ğŸš› Ship It
        uses: denoland/deployctl@v1
        with:
          project: "remix-air-metal-stack"
          entrypoint: "./build/index.js" 
          root: "./deno"
